import './globals.css'
import { Inter } from 'next/font/google'
// import Providers from "@components/Provider";
import "@/public/styles/styles.scss";
import "@/public/styles/line-awesome.min.css";
import Providers from '@/components/Provider';
import PersistLogin from "@/components/PersistLogin";
import Header2 from '@/components/Header2';
import MobileMenu from '@/components/MobileMenu';
import { Footer } from '@/components';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
      <PersistLogin>
        {children}
        
        </PersistLogin>
        </Providers>
        </body>
    </html>
  )
}
