import LoginImg from "@/public/img/worldconnected.svg";
import Image from "next/image";
import { Inter } from "next/font/google";
import "../globals.css";
// import PersistLogin from "@/components/PersistLogin";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <>
      <div className="py-[60px] lg:py-[60px] bg-[var(--bg-1)] signup-section min-h-[100vh] lg:h-[100vh] flex items-center justify-center">
        <div className="container">
          <div className="flex flex-col lg:flex-row items-center gap-4 md:gap-0 mx-3 ">
            <div className="w-full h-[100%] lg:w-1/2 md:px-5 ">{children}</div>
            <div className="w-full h-[100%] hidden lg:block lg:w-1/2 lg:pl-10 !mt-10 lg:mt-0 ">
              <Image
                src={LoginImg}
                className="w-full xxl:mr-[-200px] object-fill h-full"
                alt=""
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
