import Header2 from "@/components/Header2";
import "../globals.css";
import PersistLogin from "@/components/PersistLogin";
import Layout from "@/components/account/Layout";
import { Inter } from "next/font/google";
import MobileMenu from "@/components/MobileMenu";
import { Footer } from "@/components";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  
  return (
    <PersistLogin>
 
      <Header2 />
    <MobileMenu />
    
    <Layout>
  
      {children}

      </Layout>

      <Footer />
      
    </PersistLogin>
      
       
  );
}
