import { Footer } from "@/components";
import Header2 from "@/components/Header2";
import MobileMenu from "@/components/MobileMenu";
import Layout from "@/components/flight/Layout";
import PersistLogin from "@/components/PersistLogin";
import { Inter } from "next/font/google";
import "../globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  
  return (
 <PersistLogin>
      <Header2 />
    <MobileMenu />
    
    <Layout>
  
      {children}

      </Layout>

      <Footer />
      
      </PersistLogin>
       
  );
}
